---
- name: Add Docker apt key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add docker-ce apt repository
  ansible.builtin.apt_repository:
    repo: deb [arch={{ platform_arch }}] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    filename: docker

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker (Debian)
  ansible.builtin.package:
    state: present
    name:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
