---
- name: Ensure kustomize ksops directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(xdg_config_home, true) }}/kustomize/plugin/verumex.com/v1/ksops"
    state: directory
    mode: '0755'
  become: false
  register: ksops_dir

- name: Ensure ksops is installed
  ansible.builtin.unarchive:
    src: https://github.com/viaduct-ai/kustomize-sops/releases/download/v{{ ksops_version }}/ksops_{{ ksops_version }}_Linux_x86_64.tar.gz
    dest: "{{ ksops_dir.path }}"
    remote_src: true
    mode: '0755'
  become: false
