---
- include_tasks: "common.yml"

- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: "software_repositories_{{ ansible_os_family }}.yml"
- include_tasks: packages.yml
- include_tasks: zsh.yml
- include_tasks: fonts.yml
- include_tasks: user.yml
