---
- name: Install common packages
  ansible.builtin.package:
    state: present
    name: "{{ packages }}"

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- include_tasks: "packages_{{ ansible_os_family }}.yml"

- include_tasks: "docker_{{ ansible_os_family }}.yml"
  when: install_docker | bool

- include_tasks: "sops_{{ ansible_os_family }}.yml"
  when: install_sops | bool

- include_tasks: ksops.yml
  when: install_sops | bool
