---
- name: Add RPMFusion - Free
  ansible.builtin.yum_repository:
    name: rpmfusion-free
    description: RPM Fusion for Fedora $releasever - Free
    metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
    metadata_expire: 86400
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever

- name: Add RPMFusion - Free - Updates
  ansible.builtin.yum_repository:
    name: rpmfusion-free-updates
    description: RPM Fusion for Fedora $releasever - Free - Updates
    metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever

- name: Add RPMFusion - Nonfree
  ansible.builtin.yum_repository:
    name: rpmfusion-nonfree
    description: RPM Fusion for Fedora $releasever - Nonfree
    metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
    metadata_expire: 86400
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

- name: Add RPMFusion - Nonfree - Updates
  ansible.builtin.yum_repository:
    name: rpmfusion-nonfree-updates
    description: RPM Fusion for Fedora $releasever - Nonfree - Updates
    metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

- name: Update DNF cache
  ansible.builtin.dnf:
    update_cache: true
