---
- name: Check if sops is installed
  ansible.builtin.shell: command -v sops
  register: sops_exe
  ignore_errors: true
  changed_when: false

- name: Download sops deb package
  when: sops_exe is failed
  ansible.builtin.get_url:
    url: https://github.com/getsops/sops/releases/download/v{{ sops_version }}/sops_{{ sops_version }}_{{ platform_arch }}.deb
    dest: /tmp/sops.deb
    mode: '0755'

- name: Ensure SOPS is installed
  when: sops_exe is failed
  ansible.builtin.apt:
    deb: /tmp/sops.deb
    state: present
